# How To TReports - Instalação via Docker: https://youtu.be/Al9NoY58DJs
# TReports - Provedor de API: https://www.facebook.com/totvsdevelopers/videos/2355074714610562/?q=treports&epa=SEARCH_BOX
# RAC - http://localhost:5009/totvs.rac/.well-known/openid-configuration
version: '3.6'

networks:
  docker-network-trep:
    driver: bridge

services:
  treports:
    image: docker.totvs.io/treports/treports:12125
    environment:
      DOCKER_DBPROVIDER: "SqlServer"
      DOCKER_CONNECTIONSTRING: "Server=db;database=TRFDb_Docker;User=sa;Password=012345678@totvs123"
      DOCKER_JOB_DELAYTIME: "1"
      DOCKER_JOB_LOOPINTERATIONS: "10"
      DOCKER_LICENSE_SERVERIP: "10.80.128.51"
      DOCKER_LICENSE_SERVERPORT: "5555"
      DOCKER_HANGFIRE_USEHANGFIRE: "true"
      DOCKER_CLIENTSECRET: "totvs@123"
      DOCKER_AUTHORITYENDPOINT_SERVER: "http://rac/totvs.rac"
      DOCKER_AUTHORITYENDPOINT_CLIENT: "http://localhost:5009/totvs.rac"
      DOCKER_CLIENTID: "js_oidc_treports"
      DOCKER_DEFAULTTENANT: "empresa1"
    ports:
      - "7017:7017"
    networks:
      - docker-network-trep
    depends_on:
      - rac

  rac:
    image: docker.totvs.io/tnf/rac:1.6.4
    environment:
      DefaultSchema: "dbo"
      DefaultConnectionString: "SqlServer"
      ConnectionStrings__SqlServer: "Data Source=db;User Id=sa;Password=012345678@totvs123"
      RunMigrator: "T"
      
      Clients__0__ClientId: "rac_oidc"
      Clients__0__ClientName: "Client OIDC padrão do RAC"
      Clients__0__ProductName: "TOTVS RAC"
      Clients__0__GrantTypes__0: "Hybrid"
      Clients__0__GrantTypes__1: "ClientCredentials"
      Clients__0__ExpirationTimeInMinutes: "20"
      Clients__0__RedirectUrls__0: "http?://rac/totvs.rac/auth-callback"
      Clients__0__RedirectUrls__1: "http?://rac/totvs.rac/assets/silent-renew.html"
      Clients__0__RedirectUrls__2: "http?://localhost:5009/totvs.rac/auth-callback"
      Clients__0__RedirectUrls__3: "http?://localhost:5009/totvs.rac/assets/silent-renew.html"
      Clients__0__RedirectUrls__4: "http?://*.localhost:5009/totvs.rac/auth-callback"
      Clients__0__RedirectUrls__5: "http?://*.localhost:5009/totvs.rac/assets/silent-renew.html"
      Clients__0__LogoutUrls__0: "http?://rac/totvs.rac"
      Clients__0__LogoutUrls__1: "http?://localhost:5009/totvs.rac"
      Clients__0__LogoutUrls__2: "http?://*.localhost:5009/totvs.rac"
      Clients__0__LogoutUrls__3: "http://rac/totvs.rac"
      Clients__0__Secrets__0__Description: "Senha Padrão (totvs@123)"
      Clients__0__Secrets__0__Value: "totvs@123"

      Clients__1__ClientId: "js_oidc_treports"
      Clients__1__ClientName: "js_oidc_treports"
      Clients__1__ProductName: "TReports"
      Clients__1__GrantTypes__0: "Hybrid"
      Clients__1__GrantTypes__1: "ClientCredentials"
      Clients__1__ExpirationTimeInMinutes: "20"
      Clients__1__RedirectUrls__0: "http?://localhost:7017/auth-callback"
      Clients__1__RedirectUrls__1: "http?://localhost:7017/assets/silent-renew.html"
      Clients__1__RedirectUrls__2: "http?://*.localhost:7017/auth-callback"
      Clients__1__RedirectUrls__3: "http?://*.localhost:7017/assets/silent-renew.html"
      Clients__1__LogoutUrls__0: "http?://localhost:7017"
      Clients__1__LogoutUrls__1: "http?://*.localhost:7017"
      Clients__1__Secrets__0__Description: "Senha Padrão (totvs@123)"
      Clients__1__Secrets__0__Value: "totvs@123"

      Clients__2__ClientId: "js_oidc_sampleapp"
      Clients__2__ClientName: "js_oidc_sampleapp"
      Clients__2__ProductName: "SampleApp"
      Clients__2__GrantTypes__0: "Hybrid"
      Clients__2__GrantTypes__1: "ClientCredentials"
      Clients__2__ExpirationTimeInMinutes: "20"
      Clients__2__RedirectUrls__0: "http?://localhost:8880/auth-callback"
      Clients__2__RedirectUrls__1: "http?://localhost:8880/assets/silent-renew.html"
      Clients__2__RedirectUrls__2: "http?://*.localhost:8880/auth-callback"
      Clients__2__RedirectUrls__3: "http?://*.localhost:8880/assets/silent-renew.html"
      Clients__2__LogoutUrls__0: "http?://localhost:8880"
      Clients__2__LogoutUrls__1: "http?://*.localhost:8880"
      Clients__2__Secrets__0__Description: "Senha Padrão (totvs@123)"
      Clients__2__Secrets__0__Value: "totvs@123"

      Clients__3__ClientId: "treports_ro"
      Clients__3__ClientName: "treports_ro"
      Clients__3__ProductName: "TReports"
      Clients__3__GrantTypes__0: "ResourceOwner"
      Clients__3__ExpirationTimeInMinutes: "20"
      Clients__3__Secrets__0__Description: "Senha Padrão (totvs@123)"
      Clients__3__Secrets__0__Value: "totvs@123"

      Tenants__0__TenantName: "empresa1"
      Tenants__0__Name: "Empresa Sample"
      Tenants__0__CNPJ: "53113791001102"
      Tenants__0__Products__0__ProductName: "TOTVS RAC"
      Tenants__0__Products__1__ProductName: "TReports"
      Tenants__0__Products__2__ProductName: "SampleApp"

      HostUrl: "http://*.localhost:5009/totvs.rac"
    ports:
      - "5009:80"
    networks:
      - docker-network-trep
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu
    environment:
      SA_PASSWORD: "012345678@totvs123"
      ACCEPT_EULA: "Y"
    ports:
      - "14336:1433"
    networks:
      - docker-network-trep
